routes/web.php
<?php

use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;
use App\Models\User;
use App\Models\Client;
use Carbon\Carbon;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ContractController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\AdminTranscationController;
use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\workspace\WorkspaceDashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// login
Route::get('/', [UserController::class, 'login'])->name('/');
Route::get('/logout', [UserController::class, 'logout'])->name('logout');

// accept
Route::get('workspace/contract/accepted/{id}', [ContractController::class,'accepted'])->name('workspace.contract.accepted');
Route::get('workspace/contract/successpaiddpcontract/{id}', [ContractController::class,'successpaiddpcontract'])->name('workspace.contract.successpaiddpcontract');
Route::get('workspace/quotation/accepted/{id}', [QuotationController::class,'accepted'])->name('workspace.quotation.accepted');
Route::get('workspace/quotation/successpaiddpcontract/{id}', [QuotationController::class,'successpaiddpcontract'])->name('workspace.quotation.successpaiddpcontract');
Route::get('workspace/invoice/paynow/{id}', [InvoiceController::class,'paynow'])->name('workspace.invoice.successpaiddpcontract');
Route::get('workspace/invoice/successpaid', [InvoiceController::class,'successpaid'])->name('workspace.invoice.succespaid');


Route::middleware(['guest'])->group(function () {
    Route::get('/', [UserController::class, 'login'])->name('/');
    Route::get('/login', [UserController::class, 'login'])->name('login');
    Route::post('/login-proses', [UserController::class, 'login_proses'])->name('login-proses');
    Route::get('/forgot-password', [UserController::class, 'forgotPasswordShow'])->name('forgot-password');
    Route::post('/forgot-password', [UserController::class, 'forgotPassword'])->name('forgot-password.store');
    Route::get('/reset-password/{token}', [UserController::class, 'resetPassword'])->name('password.reset');
    Route::post('/reset-password', [UserController::class, 'resetPasswordProses'])->name('password.reset.store');
});

Route::middleware(['guest'])->name('password.reset')->prefix('reset-password')->group(function () {
    Route::get('/{token}', [UserController::class, 'resetPassword'])->name('');
});

Route::get('/loginadmin', [UserController::class, 'loginadmin'])->name('loginadmin')->middleware('guest');
Route::get('/register', [UserController::class, 'register'])->name('register')->middleware('guest');
Route::post('/register-proses', [UserController::class, 'register_proses'])->name('register-proses')->middleware('guest');


Route::group(['prefix' => 'workspace', 'middleware' => ['auth'], 'as' => 'workspace.'], function () {

    Route::get('/dashboard', [WorkspaceDashboardController::class, 'index'])->name('dashboard');

    Route::get('/clients', [ClientController::class, 'index'])->name('clients');

    Route::post('/clients/create', [ClientController::class, 'store'])->name('clients.store');

    Route::get('/clients/edit/{id}', [ClientController::class, 'edit'])->name('clients.edit');

    Route::put('/clients/update/{id}', [ClientController::class, 'update'])->name('clients.update');

    Route::put('/clients/show/update/notes/{id}', [ClientController::class, 'updateNotes'])->name('clients.update.notes');

    Route::put('/clients/show/update/name/{id}', [ClientController::class, 'updateNameClient'])->name('clients.update.name');

    Route::delete('/clients/delete/{id}', [ClientController::class, 'destroy'])->name('clients.delete');

    Route::get('/clients/show/{id}', [ClientController::class, 'show'])->name('clients.show');

    Route::post('/clients/show/tasks/send/{id}', [ClientController::class, 'tasks'])->name('clients.send.tasks');

    Route::delete('/clients/show/tasks/destroy/{id}', [ClientController::class, 'tasksDestroy'])->name('clients.tasks.destroy');

    Route::get('/clients/checklimit/{id}', [ClientController::class, 'checklimit'])->name('clients.checklimit');

    Route::get('/projects', [ProjectController::class, 'index'])->name('projects');
    Route::put('/projects/update/{id}', [ProjectController::class, 'update'])->name('projects.update');
    Route::delete('/projects/delete/{id}', [ProjectController::class, 'destroy'])->name('projects.delete');
    Route::get('/projects/show/{id}', [ProjectController::class, 'show'])->name('projects.show');
    Route::put('/projects/show/update/name/{id}', [ProjectController::class, 'updateName'])->name('projects.update.name');
    Route::post('/projects/store', [ProjectController::class, 'store'])->name('projects.store');
    Route::get('/projects/showadd', [ProjectController::class, 'showadd'])->name('projects.showadd');
    Route::get('/projects/detail/{id}', [ProjectController::class, 'detail'])->name('projects.detail');
    
    // quotations
    Route::get('/quotation', [QuotationController::class, 'index'])->name('quotation');
    Route::get('/quotation/showadd', [QuotationController::class, 'showadd'])->name('quotation.showadd');
    Route::get('/quotation/create', [QuotationController::class, 'create'])->name('quotation.create');
    Route::get('/quotation/edit/{id}', [QuotationController::class, 'edit'])->name('quotation.edit');
    Route::get('/quotation/update/{id}', [QuotationController::class, 'update'])->name('quotation.update');
    Route::get('/quotation/delete/{id}', [QuotationController::class, 'delete'])->name('quotation.delete');
    Route::get('/quotation/show/{id}', [QuotationController::class, 'show'])->name('quotation.show');
    Route::post('/quotation/store', [QuotationController::class, 'store'])->name('quotation.store');
    Route::get('/quotation/review/{id}', [QuotationController::class, 'review'])->name('quotation.review');
    Route::get('/quotation/pdf/{id}', [QuotationController::class, 'pdf'])->name('quotation.pdf');
    Route::post('/quotation/status/{id}', [QuotationController::class, 'status'])->name('quotation.pdf');
    Route::get('/quotation/editemail/{id}', [QuotationController::class, 'showEditEmail'])->name('quotation.editemail');
    Route::post('/quotation/finishemail/{id}', [QuotationController::class, 'finishemail'])->name('quotation.finishemail');
    Route::get('/quotation/showupdate/{id}', [QuotationController::class, 'showUpdate'])->name('quotation.showupdate');
    Route::put('/quotation/update/{id}', [QuotationController::class, 'update'])->name('quotation.update');
    Route::get('/quotation/showeditreview/{id}', [QuotationController::class,'showeditreview'])->name('quotation.showeditreview');
    Route::get('/quotation/editreview', [QuotationController::class,'editreview'])->name('quotation.editreview');
    Route::delete('/quotation/deleteQuotation/{id}', [QuotationController::class,'deleteQuotation'])->name('quotation.deleteQuotation');

    // contract
    Route::get('/contract', [ContractController::class, 'index'])->name('contract');
    Route::get('/contract/showadd', [ContractController::class, 'showadd'])->name('contract.showadd');
    Route::post('/contract/store', [ContractController::class, 'store'])->name('contract.store');
    Route::get('/contract/review/{id}', [ContractController::class, 'review'])->name('contract.review');
    Route::get('/contract/sendemail/{id}',[ContractController::class,'sendemail'])->name('contract.sendemail');
    Route::post('/contract/finishemail/{id}', [ContractController::class, 'finishemail'])->name('contract.finishemail');
    Route::get('/contract/showupdate/{id}', [ContractController::class, 'showUpdate'])->name('contract.showupdate');
    Route::put('/contract/update/{id}', [ContractController::class, 'update'])->name('contract.update');
    Route::get('/contract/showeditterm/{id}', [ContractController::class,'showeditterm'])->name('contract.showeditterm');
    Route::put('/contract/editterm/{id}', [ContractController::class,'editterm'])->name('contract.editterm');
    Route::delete('/contract/deleteContract/{id}', [ContractController::class, 'deleteContract'])->name('contract.deleteContract');    
    
    // invoice
    Route::get('/invoice', [InvoiceController::class, 'index'])->name('invoice');
    Route::get('/invoice/show/{id}', [InvoiceController::class, 'showId'])->name('invoices.show');
    Route::post('/invoice/create', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::put('/invoice/update/{id}', [InvoiceController::class, 'update'])->name('invoices.update');
    Route::get('/invoice/create', [InvoiceController::class, 'createInvoiceShowStep1'])->name('invoices.createInvoiceShowStep1');

    Route::get('/invoice/create', [InvoiceController::class, 'showAdd'])->name('invoices.showAdd');

    Route::post('invoce/create', [InvoiceController::class, 'postShowAdd'])->name('invoices.postShowAdd');

    Route::post('/invoice/print', [InvoiceController::class, 'printPDF'])->name('invoices.print');
    Route::delete('/invoice/delete/{id}', [InvoiceController::class, 'destroy'])->name('invoices.delete');
    Route::get('/invoice/createfromproject/{id}', [InvoiceController::class, 'showInvoiceFromProject'])->name('invoices.createfromproject');
    // Post Create Invoice
    Route::get('/invoice/create/preview', function () {

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use App\Models\TasksClient;
use App\Models\ProjectModel;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    public function index()
    {
        // Hitung jumlah pengguna yang mendaftar dalam satu minggu terakhir
        $userCountLastWeek = User::whereBetween('created_at', [Carbon::now()->subWeek(), Carbon::now()])->count();

        // Hitung jumlah total pengguna
        $userCount = User::count();

        // Hitung jumlah klien yang didaftarkan dalam satu minggu terakhir
        $clientCountLastWeek = Client::whereBetween('created_at', [Carbon::now()->subWeek(), Carbon::now()])->count();

        // Hitung jumlah total klien
        $clientCount = Client::count();

        $userId = Auth::id();

        if (Auth::user()->id_role == 3) {
            $client = Client::where('user_id', $userId)->limit(5)->get();
        } else {
            $client = Client::where('user_id', $userId)->paginate(5);
        }

        return view('workspace.clients.index', [
            'userCountLastWeek' => $userCountLastWeek,
            'userCount' => $userCount,
            'clientCountLastWeek' => $clientCountLastWeek,
            'clientCount' => $clientCount,
            'client' => $client,
            'only5' => Auth::user()->id_role == 3 ? true : false,
        ]);
    }

    public function store(Request $request)
    {
        $data = [
            'name' => $request->name,
            'address' => $request->address,
            'state' => $request->state,
            'city' => $request->city,
            'region' => $request->region,
            'postal_code' => $request->postal_code,
            'no_telp' => $request->no_telp,
            'user_id' => auth()->user()->id,
            'email' => $request->email,
        ];
        if (!$data) {
            Alert::error('Failed Message', 'You have failed add new Client.');
            return redirect()->route('workspace.clients');

        } else {
            Alert::success('Success Message', 'You have successfully add new Client.');
            Client::create($data);
            return redirect()->route('workspace.clients');
        }

    }

    public function edit($id)
    {
        $client = Client::find($id);

        return view('workspace.clients.edit', compact('client'));
    }

    public function update(Request $request, $id){
        $validator = Validator::make($request->all(), [
            'email' => ['required', 'email:dns', 'unique:clients,email'],
            'address' => ['required'],
            'no_telp' => ['required'],
            'postal_code' => ['required'],
            'state' => ['required'],
            'city' => ['required'],
            'region' => ['required'],
        ]);
        if ($validator->fails()) {
            Alert::error('Failed Message', 'You have failed to edit client.')->withErrors($validator);
            return redirect()->back();
        }
        $data = [
            'email' => $request->email,
            'address' => $request->address,
            'no_telp' => $request->no_telp,
            'email' => $request->email,
            'postal_code' => $request->postal_code,
            'state' => $request->state,
            'city' => $request->city,
            'region' => $request->region,
        ];
        if (!$data) {
            Alert::error('Failed Message', 'You have failed to edit client.');
            return redirect()->back();
        } else {
            Alert::success('Success Message', 'You have successfully to edit client.');
            Client::find($id)->update($data);
            return redirect()->back();

        }
        return redirect()->route('workspace.clients.show', ['#tabs-address'], $id);
    }

    public function updateNotes(Request $request, $id) {
        $client = Client::find($id);
        if (!$client) {
            return redirect()->back()->with('error', 'Client not found');
        }
    
        $client->notes = $request->notes;
        $client->save();
    
        Alert::success('Success Message', 'You have successfully changed the notes.');
        return redirect()->back();
    }

    public function tasks(Request $request, $id) {
        $client = Client::find($id);
        $user = Auth()->user()->id;
        $data = [
            'tasks' => $request->tasks,
            'tasks_due_date' => $request->tasks_due_date,
            'id_client' => $id,
            'id_user' => $user
        ];
        if($request->tasks === null || $request->tasks_due_date === null) {
            Alert::error('Failed Message', 'You have failed to add tasks.');
            return redirect()->back();
        } else {
            if (!$data) {
                Alert::error('Failed Message', 'You have failed to add tasks.');
                return redirect()->route('workspace.clients.show', $id);
            } else {
                TasksClient::create($data);
                return redirect()->route('workspace.clients.show', $id);
    
            }
            return redirect()->route('workspace.clients.show', $client->id);
        }
        
    }

    public function updateNameClient(Request $request, $id){
        $client = Client::find($id);
        if (!$client) {
            return redirect()->back()->with('error', 'Client not found');
        }
    
        $client->name = $request->name;
        $client->save();
    
        Alert::success('Success Message', 'You have successfully changed the name.');
        return redirect()->back();

    }

    public function show($id)
    {
        $user = Auth::user();
        $client = Client::where('user_id', $user->id)->findOrFail($id);
        $projectmodels = ProjectModel::where('id_client', $id)->paginate(10);
        $tasks = TasksClient::where('id_client', $id)->get();
    
    
        return view('workspace.clients.show', compact('client', 'tasks', 'projectmodels'));
    }

    public function destroy($id)
    {
        $client = Client::find($id);
        if ($client->id_role == 1) {
            Alert::error('Failed Message', 'You have failed delete Client.');
            return redirect()->route('workspace.clients')->with('failed', 'Gagal menghapus Client!');
        }

        $client->delete();
        Alert::success('Success Message', 'You have successfully delete.');
        return redirect()->route('workspace.clients');
    }

    public function tasksDestroy($id){
        $tasks = TasksClient::find($id);
        $tasks->delete();
        return redirect()->back();
    }

    public function checklimit($id)
    {
        $user = User::find($id);
        if ($user->id_role == 3) {
            // check bila sudah limit 
            $client = Client::where('user_id', $id)->count();
            if ($client < 5) {
                return back()->with('aman', 'aman');
            } else {
                return back()->with('limit', 'limit');
            }
        } else {
            return back()->with('aman', 'aman');
        }
    }


}

resources/views/workspace/clients/index.blade.php
@extends('template')

@php
    $title = 'Client List';
@endphp


@section('body')
    @include('workspace.component.letsupgrade')
    <div class="row row-deck row-cards">
        @include('workspace.header')
        <div class="col-12">
               <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Search Filter</h3>
                </div>
                <div class="card-body border-bottom py-3">
                    <div class="d-flex">
                        <div class="text-muted">
                            <select class="form-select" aria-label="Default select example">
                                <option selected>Select Plan</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                        <div class="text-muted ms-3">
                            <select class="form-select" aria-label="Default select example">
                                <option selected>Select Plan</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>
                        <div class="ms-auto me-3">
                            <select class="form-select" id="select">
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="50">50</option>
                                <!-- Tambahkan opsi lain sesuai kebutuhan -->
                            </select>
                        </div>
                        <form action="{{ route('workspace.clients.checklimit', ['id' => Auth::user()->id]) }}"
                            method="GET">
                            @csrf
                            <button type="submit" class="btn btn-primary font-weight-bolder" data-bs-toggle="modal">
                                New Client
                            </button>
                        </form>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table card-table table-vcenter text-nowrap datatable table-hover">
                        <thead>
                            <tr>
                                <th class="w-1">No.
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-sm icon-thick" width="24"
                                        height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                        fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M6 15l6 -6l6 6" />
                                    </svg>
                                </th>
                                <th>Client</th>
                                <th>Email</th>
                                <th>Alamat</th>
                                <th>Nomor HP</th>
                                {{-- <th>Status</th> --}}
                                <th class="w-1"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                if($only5 == true){
                                    $i = 1;
                                }else{
                                    $i = 1 + ($client->currentPage() - 1) * $client->perPage();
                                }
                            @endphp
                            @foreach ($client as $clients)
                                <tr onclick="window.location='{{ route('workspace.clients.show', $clients->id) }}'" style="cursor: pointer;">
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $clients->name }}</td>
                                    <td>{{ $clients->email }}</td>
                                    <td>{{ $clients->address }}</td>
                                    <td>{{ $clients->no_telp }}</td>
                                    <td></td>
                                </tr>
                            @endforeach



                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex align-items-center ms-auto">
                    @if ($only5 != true)
                    {!! $client->appends(Request::except('page'))->links('pagination::bootstrap-5') !!}
                    @endif
                </div>
                {{-- Modal Dialog --}}
                <div class="modal fade" id="tambah_client" tabindex="-1" aria-labelledby="modal2Label"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modal2Label">Add new client</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="{{ route('workspace.clients.store') }}" method="POST"
                                    enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="col-md-12 mt-2">
                                            <div class="form-group">
                                                <label for="nama_cabang">Nama Client</label>
                                                <input type="text" class="form-control mt-1" name="name"
                                                    placeholder="Masukkan nama client" required />
                                                @error('name')
                                                    <div class="invalid-feedback">
                                                        {{ $message }}
                                                    </div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-md-12 mt-2">
                                            <div class="form-group">
                                                <label for="Email">Email</label>
                                                <input type="text" class="form-control mt-1 @error('email')is-invalid @enderror" name="email"
                                                    placeholder="Masukkan Email" required />
                                                @error('email')
                                                    <div class="invalid-feedback">
                                                        {{ $message }}
                                                    </div>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="col-md-12 mt-2">
                                            <div class="form-group">
                                                <label for="address">Address</label>
                                                <textarea class="form-control mt-1  " name="address" rows="3" placeholder="Masukkan Alamat"></textarea>
                                                @error('address')
                                                    <div class="invalid-feedback">
                                                        {{ $message }}
                                                    </div>
                                                @enderror
                                            </div>
                                            <div class="row mt-2">
                                                <div class="col-lg-6">
                                                      <label class="form-label">State</label>
                                                      <input type="text" name="state" class="form-control" placeholder="Masukan Negaramu">
                                                  </div>
                                                  <div class="col-lg-6">
                                                      <label class="form-label">City</label>
                                                      <input type="text" class="form-control" name="city" placeholder="Masukan Kotamu">
                                                  </div>
                                            </div>
                                            <div class="row mt-2">
                                                <div class="col-lg-6">
                                                      <label class="form-label">Province</label>
                                                      <input type="text" name="region" class="form-control" placeholder="Masukan Provinsimu">
                                                  </div>
                                                  <div class="col-lg-6">
                                                      <label class="form-label">Zip Code</label>
                                                      <input type="number" class="form-control" name="postal_code" placeholder="Masukan Kodepos mu">
                                                  </div>
                                            </div>
                                            <div class="col-md-12 mt-2">
                                                <div class="form-group">
                                                    <label for="no_telp">Nomor HP</label>
                                                    <input type="text" class="form-control mt-1" id="no_telp"
                                                        name="no_telp" placeholder="Masukkan Nomor HP" required />
                                                    @error('no_telp')
                                                        <div class="invalid-feedback">
                                                            {{ $message }}
                                                        </div>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kembali</button>
                                <button type="submit" class="btn btn-primary mr-2">Tambah</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- add ajax --}}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    @if (session('limit'))
        <script>
            // Pastikan dokumen sudah dimuat sepenuhnya
            document.addEventListener("DOMContentLoaded", function() {
                // Periksa apakah sesi 'aman' bernilai true
                // Tampilkan modal tambah_client
                $('#modal-scrollable').modal('show');
            });
        </script>
    @endif

    @if (session('aman'))
        <script>
            // Pastikan dokumen sudah dimuat sepenuhnya
            document.addEventListener("DOMContentLoaded", function() {
                // Periksa apakah sesi 'aman' bernilai true
                // Tampilkan modal tambah_client
                $('#tambah_client').modal('show');
            });
        </script>
    @endif
@endsection

@section('sweetalert')
    <script>
        // Auto-close the alert messages after 3 seconds (3000 milliseconds)
        setTimeout(function() {
            $('.swal2-popup').fadeOut();
        }, 3000);
    </script>
@endsection