routes/web.php
<?php

use App\Http\Controllers\TransactionController;
use Illuminate\Support\Facades\Route;
use App\Models\User;
use App\Models\Client;
use Carbon\Carbon;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ContractController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\AdminTranscationController;
use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\workspace\WorkspaceDashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// login
Route::get('/', [UserController::class, 'login'])->name('/');
Route::get('/logout', [UserController::class, 'logout'])->name('logout');

// accept
Route::get('workspace/contract/accepted/{id}', [ContractController::class,'accepted'])->name('workspace.contract.accepted');
Route::get('workspace/contract/successpaiddpcontract/{id}', [ContractController::class,'successpaiddpcontract'])->name('workspace.contract.successpaiddpcontract');
Route::get('workspace/quotation/accepted/{id}', [QuotationController::class,'accepted'])->name('workspace.quotation.accepted');
Route::get('workspace/quotation/successpaiddpcontract/{id}', [QuotationController::class,'successpaiddpcontract'])->name('workspace.quotation.successpaiddpcontract');
Route::get('workspace/invoice/paynow/{id}', [InvoiceController::class,'paynow'])->name('workspace.invoice.successpaiddpcontract');
Route::get('workspace/invoice/successpaid', [InvoiceController::class,'successpaid'])->name('workspace.invoice.succespaid');


Route::middleware(['guest'])->group(function () {
    Route::get('/', [UserController::class, 'login'])->name('/');
    Route::get('/login', [UserController::class, 'login'])->name('login');
    Route::post('/login-proses', [UserController::class, 'login_proses'])->name('login-proses');
    Route::get('/forgot-password', [UserController::class, 'forgotPasswordShow'])->name('forgot-password');
    Route::post('/forgot-password', [UserController::class, 'forgotPassword'])->name('forgot-password.store');
    Route::get('/reset-password/{token}', [UserController::class, 'resetPassword'])->name('password.reset');
    Route::post('/reset-password', [UserController::class, 'resetPasswordProses'])->name('password.reset.store');
});

Route::middleware(['guest'])->name('password.reset')->prefix('reset-password')->group(function () {
    Route::get('/{token}', [UserController::class, 'resetPassword'])->name('');
});

Route::get('/loginadmin', [UserController::class, 'loginadmin'])->name('loginadmin')->middleware('guest');
Route::get('/register', [UserController::class, 'register'])->name('register')->middleware('guest');
Route::post('/register-proses', [UserController::class, 'register_proses'])->name('register-proses')->middleware('guest');


Route::group(['prefix' => 'workspace', 'middleware' => ['auth'], 'as' => 'workspace.'], function () {

    Route::get('/dashboard', [WorkspaceDashboardController::class, 'index'])->name('dashboard');

    Route::get('/clients', [ClientController::class, 'index'])->name('clients');

    Route::post('/clients/create', [ClientController::class, 'store'])->name('clients.store');

    Route::get('/clients/edit/{id}', [ClientController::class, 'edit'])->name('clients.edit');

    Route::put('/clients/update/{id}', [ClientController::class, 'update'])->name('clients.update');

    Route::put('/clients/show/update/notes/{id}', [ClientController::class, 'updateNotes'])->name('clients.update.notes');

    Route::put('/clients/show/update/name/{id}', [ClientController::class, 'updateNameClient'])->name('clients.update.name');

    Route::delete('/clients/delete/{id}', [ClientController::class, 'destroy'])->name('clients.delete');

    Route::get('/clients/show/{id}', [ClientController::class, 'show'])->name('clients.show');

    Route::post('/clients/show/tasks/send/{id}', [ClientController::class, 'tasks'])->name('clients.send.tasks');

    Route::delete('/clients/show/tasks/destroy/{id}', [ClientController::class, 'tasksDestroy'])->name('clients.tasks.destroy');

    Route::get('/clients/checklimit/{id}', [ClientController::class, 'checklimit'])->name('clients.checklimit');

    Route::get('/projects', [ProjectController::class, 'index'])->name('projects');
    Route::put('/projects/update/{id}', [ProjectController::class, 'update'])->name('projects.update');
    Route::delete('/projects/delete/{id}', [ProjectController::class, 'destroy'])->name('projects.delete');
    Route::get('/projects/show/{id}', [ProjectController::class, 'show'])->name('projects.show');
    Route::put('/projects/show/update/name/{id}', [ProjectController::class, 'updateName'])->name('projects.update.name');
    Route::post('/projects/store', [ProjectController::class, 'store'])->name('projects.store');
    Route::get('/projects/showadd', [ProjectController::class, 'showadd'])->name('projects.showadd');
    Route::get('/projects/detail/{id}', [ProjectController::class, 'detail'])->name('projects.detail');
    
    // quotations
    Route::get('/quotation', [QuotationController::class, 'index'])->name('quotation');
    Route::get('/quotation/showadd', [QuotationController::class, 'showadd'])->name('quotation.showadd');
    Route::get('/quotation/create', [QuotationController::class, 'create'])->name('quotation.create');
    Route::get('/quotation/edit/{id}', [QuotationController::class, 'edit'])->name('quotation.edit');
    Route::get('/quotation/update/{id}', [QuotationController::class, 'update'])->name('quotation.update');
    Route::get('/quotation/delete/{id}', [QuotationController::class, 'delete'])->name('quotation.delete');
    Route::get('/quotation/show/{id}', [QuotationController::class, 'show'])->name('quotation.show');
    Route::post('/quotation/store', [QuotationController::class, 'store'])->name('quotation.store');
    Route::get('/quotation/review/{id}', [QuotationController::class, 'review'])->name('quotation.review');
    Route::get('/quotation/pdf/{id}', [QuotationController::class, 'pdf'])->name('quotation.pdf');
    Route::post('/quotation/status/{id}', [QuotationController::class, 'status'])->name('quotation.pdf');
    Route::get('/quotation/editemail/{id}', [QuotationController::class, 'showEditEmail'])->name('quotation.editemail');
    Route::post('/quotation/finishemail/{id}', [QuotationController::class, 'finishemail'])->name('quotation.finishemail');
    Route::get('/quotation/showupdate/{id}', [QuotationController::class, 'showUpdate'])->name('quotation.showupdate');
    Route::put('/quotation/update/{id}', [QuotationController::class, 'update'])->name('quotation.update');
    Route::get('/quotation/showeditreview/{id}', [QuotationController::class,'showeditreview'])->name('quotation.showeditreview');
    Route::get('/quotation/editreview', [QuotationController::class,'editreview'])->name('quotation.editreview');
    Route::delete('/quotation/deleteQuotation/{id}', [QuotationController::class,'deleteQuotation'])->name('quotation.deleteQuotation');

    // contract
    Route::get('/contract', [ContractController::class, 'index'])->name('contract');
    Route::get('/contract/showadd', [ContractController::class, 'showadd'])->name('contract.showadd');
    Route::post('/contract/store', [ContractController::class, 'store'])->name('contract.store');
    Route::get('/contract/review/{id}', [ContractController::class, 'review'])->name('contract.review');
    Route::get('/contract/sendemail/{id}',[ContractController::class,'sendemail'])->name('contract.sendemail');
    Route::post('/contract/finishemail/{id}', [ContractController::class, 'finishemail'])->name('contract.finishemail');
    Route::get('/contract/showupdate/{id}', [ContractController::class, 'showUpdate'])->name('contract.showupdate');
    Route::put('/contract/update/{id}', [ContractController::class, 'update'])->name('contract.update');
    Route::get('/contract/showeditterm/{id}', [ContractController::class,'showeditterm'])->name('contract.showeditterm');
    Route::put('/contract/editterm/{id}', [ContractController::class,'editterm'])->name('contract.editterm');
    Route::delete('/contract/deleteContract/{id}', [ContractController::class, 'deleteContract'])->name('contract.deleteContract');    
    
    // invoice
    Route::get('/invoice', [InvoiceController::class, 'index'])->name('invoice');
    Route::get('/invoice/show/{id}', [InvoiceController::class, 'showId'])->name('invoices.show');
    Route::post('/invoice/create', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::put('/invoice/update/{id}', [InvoiceController::class, 'update'])->name('invoices.update');
    Route::get('/invoice/create', [InvoiceController::class, 'createInvoiceShowStep1'])->name('invoices.createInvoiceShowStep1');

    Route::get('/invoice/create', [InvoiceController::class, 'showAdd'])->name('invoices.showAdd');

    Route::post('invoce/create', [InvoiceController::class, 'postShowAdd'])->name('invoices.postShowAdd');

    Route::post('/invoice/print', [InvoiceController::class, 'printPDF'])->name('invoices.print');
    Route::delete('/invoice/delete/{id}', [InvoiceController::class, 'destroy'])->name('invoices.delete');
    Route::get('/invoice/createfromproject/{id}', [InvoiceController::class, 'showInvoiceFromProject'])->name('invoices.createfromproject');
    // Post Create Invoice
    Route::get('/invoice/create/preview', function () {

app/Models/Quotation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
class Quotation extends Model
{
    use HasFactory;

    protected $fillable=[
        'quotation_name',
        'start_date',
        'end_date',
        'status',
        'quotation_pdf',
        'id_client',
        'id_project',
        'id_user',
        'require_deposit',
        'deposit_amount',
        'deposit_percentage',
        'client_agrees_deposit',
        'final_invoice_date'
    ];

    public function client() : BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function project() : HasOne
    {
        return $this->hasOne(ProjectModel::class);
    }

    public function service() : HasMany
    {
        return $this->hasOne(Service::class);
    }
}

app/Http/Controllers/workspace/WorkspaceDashboardController.php
<?php

namespace App\Http\Controllers\workspace;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Client;
use Carbon\Carbon;

class WorkspaceDashboardController extends Controller
{
    public function index()
    {
        // Hitung jumlah pengguna yang mendaftar dalam satu minggu terakhir
        $userCountLastWeek = User::whereBetween('created_at', [Carbon::now()->subWeek(), Carbon::now()])->count();
    
        // Hitung jumlah total pengguna
        $userCount = User::count();
    
        // Hitung jumlah klien yang didaftarkan dalam satu minggu terakhir
        $clientCountLastWeek = Client::whereBetween('created_at', [Carbon::now()->subWeek(), Carbon::now()])->count();
    
        // Hitung jumlah total klien
        $clientCount = Client::count();
    
        // Mengirimkan data ke tampilan Blade
        return view('workspace.dashboard', [
            'userCountLastWeek' => $userCountLastWeek,
            'userCount' => $userCount,
            'clientCountLastWeek' => $clientCountLastWeek,
            'clientCount' => $clientCount
        ]);
    }
}

resources/views/workspace/quotation/acceptpage.blade.php
@extends('clienttemplate')

@section('body')
    <div class="container container-tight" style="margin-top: 130px;">
        <div class="card" style="height: 200px;">
            <div class="card-status-top bg-green"></div>
            <div class="card-header">
                <h3 class="card-title">Succesfully Accepting Project!</h3>
            </div>
            <div class="card-body p-0">
                <div class="text-center mt-3">
                    <h4>Thank You For Accepting Project</h4>
                    <p>You have successfully accepted the project, come back to check it</p>
                    <a href="{{ route('workspace.contract') }}" class="btn btn-primary">Go Back!</a>
                </div>
            </div>
        </div>
    </div>
   
@endsection

resources/views/workspace/quotation/editemail.blade.php
@extends('template')

@section('body')
    <div class="container">
        <h1>Edit Email</h1>
        <form action="{{ route('workspace.quotation.finishemail', $quotation->id) }}" method="POST">
            @csrf
            <div class="mb-3">
                <label for="recipient" class="form-label">To:</label>
                <input type="text" class="form-control" id="recipient" name="recipient" value="{{ $client->email }}" required>
            </div>
            <div class="mb-3">
                <label for="subject" class="form-label">Subject:</label>
                <input type="text" class="form-control" id="subject" name="subject" value="{{ $quotation->quotation_name }}" required>
            </div>
            <div class="mb-3">
                <label for="message" class="form-label">Message:</label>
                <textarea class="form-control" id="message" name="message" rows="6" required></textarea>
            </div>
            <div class="mb-3">
                <button type="button" class="btn btn-secondary">Preview Email</button>
                <button type="submit" class="btn btn-primary">Send Email</button>
            </div>
        </form>
    </div>
@endsection

resources/views/workspace/quotation/editreview.blade.php
<!-- resources/views/workspace/quotation/review.blade.php -->

@extends('template')

@section('body')
<div class="container">   
    <div class="row mb-3">
        <div class="col">
            <h3 class="card-title">Review Quotation</h3>
        </div>
        <div class="col d-flex justify-content-end">
            <form action="{{ route('workspace.quotation.editreview') }}" class="mt-4">
                @csrf
                <button type="submit" class="btn btn-primary">Done</button>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Quotation Details</h3>
        </div>
        <div class="card-body">
            <p><strong>Project Name:</strong> {{ $quotation->quotation_name }}</p>
            <p><strong>Client Name:</strong> {{ $client->name }}</p>
            <p><strong>Start Date:</strong> {{ $quotation->start_date }}</p>
            @if ($quotation->end_date)
                <p><strong>End Date:</strong> {{ $quotation->end_date }}</p>
            @else
                <p><strong>End Date:</strong> Open Date</p>                
            @endif
            <p><strong>Final Invoice Date:</strong> {{ $quotation->final_invoice_date }}</p>
            <p><strong>Require Deposit:</strong> {{ $quotation->require_deposit ? 'Yes' : 'No' }}</p>
            @if ($quotation->require_deposit)
                <p><strong>Deposit Percentage:</strong> {{ $quotation->deposit_percentage }}%</p>
                <p><strong>Deposit Amount:</strong> ${{ $quotation->deposit_amount }}</p>
                <p><strong>Client Agrees to Deposit:</strong> {{ $quotation->client_agrees_deposit ? 'Yes' : 'No' }}</p>
            @endif
        </div>
    </div>
    <div class="card mt-4">
        <div class="card-header">
            <h3 class="card-title">Services</h3>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>Price</th>
                        <th>Fee Method</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($serviceDetails as $service)
                        <tr>
                            <td>{{ $service->service_name }}</td>
                            <td>{{ $service->price }}</td>
                            <td>{{ $service->pay_method }}</td>
                            <td>{{ $service->description }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
@endsection

resources/views/workspace/quotation/index.blade.php
@extends('template')

@php
  $title= "Quotation";
@endphp

@section('body')
    <div class="row row-deck row-cards">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">quotations</h3>
                </div>

                <div class="card-body border-bottom py-3">
                    <a href="{{ route('workspace.quotation.showadd') }}">
                        <button type="button" class="btn btn-primary font-weight-bolder" data-bs-toggle="modal">
                            New Quotation
                        </button>
                    </a>
                </div>
                <div class="table-responsive">
                    <table class="table card-table table-vcenter text-nowrap datatable">
                        <thead>
                            <tr>
                                <th class="w-1">No.
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-sm icon-thick" width="24"
                                        height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                        fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path d="M6 15l6 -6l6 6" />
                                    </svg>
                                </th>
                                <th>quotation Name</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Status</th>
                                <th>Client</th>
                                {{-- <th>Freelancer</th> --}}
                                <th class="w-1"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $i = 1 + ($quotations->currentPage() - 1) * $quotations->perPage();
                            @endphp
                            @foreach ($quotations as $quotation)
                                <tr>
                                    <td><span class="text-muted">{{ $i++ }}</span></td>
                                    <td>{{ $quotation->quotation_name }}</td>
                                    <td>{{ $quotation->start_date }}</td>
                                    {{-- jika end date null isi dengan - --}}
                                    <td>{{ $quotation->end_date == null ? '-' : $quotation->end_date }}</td>
                                    <td>
                                        @if ($quotation->status == 'APPROVED')
                                            <span class="badge text-bg-success">{{ $quotation->status }}</span>
                                        @elseif($quotation->status == 'SENT')
                                            <span class="badge text-bg-warning">{{ $quotation->status }}</span>
                                        @elseif($quotation->status == 'DISMISSED')
                                            <span class="badge text-bg-danger">{{ $quotation->status }}</span>
                                        @endif
                                    </td>
                                    <td>{{ $quotation->name }}</td>
                                    {{-- <td>{{ $quotation->fullname }}</td> --}}
                                    <td>
                                        <div class="btn-group mb-1 dropleft ">
                                            <div class="dropdown dropleft">
                                                <button class="btn btn-primary dropdown-toggle me-1" type="button"
                                                    id="dropdownMenuButtonIcon" data-bs-toggle="dropdown"
                                                    aria-haspopup="true" aria-expanded="false">
                                                    Aksi
                                                </button>
                                                <div class="dropdown-menu dropdown-menu-end">
                                                    <a href={{ route('workspace.quotation.showupdate', $quotation->id) }}><button
                                                        class="dropdown-item">
                                                        Edit
                                                    </button></a>
                                                <button class="dropdown-item" data-bs-toggle="modal"
                                                    data-bs-target="#modalDelete-{{ $quotation->id }}">Delete</button>
                                                <a href={{ route('workspace.quotation.editemail', $quotation->id) }}>
                                                    <button class="dropdown-item">

                                                        Send Email</button></a>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>

                                {{-- Modal Hapus --}}
                                <div class="modal modal-blur fade" id="modalDelete-{{ $quotation->id }}"
                                    aria-hidden="true">
                                    <div class="modal-dialog modal-lg modal-dialog-centered">
                                        <div class="modal-content">
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                            <div class="modal-status bg-danger"></div>
                                            <div class="modal-body text-center py-4">
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                    class="icon mb-2 text-danger icon-lg" width="24" height="24"
                                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                                    fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                                    <path d="M12 9v4"></path>
                                                    <path
                                                        d="M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0z">
                                                    </path>
                                                    <path d="M12 16h.01"></path>
                                                </svg>
                                                <h3>Are you sure?</h3>
                                                <div class="text-secondary">Do you really want to remove quotation
                                                    {{ $quotation->quotation_name }}? What you've done cannot be undone.
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <div class="w-100">
                                                    <div class="row">
                                                        <form
                                                            action="{{ route('workspace.quotation.deleteQuotation', ['id' => $quotation->id]) }}"
                                                            method="POST">
                                                            @csrf
                                                            @method('DELETE')
                                                            <div class="col">
                                                                <a href="#" class="btn w-100"
                                                                    data-bs-dismiss="modal">Cancel</a>
                                                            </div>
                                                            <div class="col">
                                                                <button type="submit" class="btn btn-danger w-100"
                                                                    data-bs-dismiss="modal">Delete</button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach

                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex align-items-center ms-auto">
                    {!! $quotations->appends(Request::except('page'))->links('pagination::bootstrap-5') !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('sweetalert')
    <script>
        // Auto-close the alert messages after 3 seconds (3000 milliseconds)
        setTimeout(function() {
            $('.swal2-popup').fadeOut();
        }, 3000);
    </script>
@endsection

resources/views/workspace/quotation/review.blade.php
<!-- resources/views/workspace/quotation/review.blade.php -->

@extends('template')

@section('body')
<div class="container">   
    <div class="row mb-3">
        <div class="col">
            <h3 class="card-title">Review Quotation</h3>
        </div>
        <div class="col d-flex justify-content-end">
            <form action="{{ route('workspace.quotation.editemail', $quotation->id) }}" method="post" class="mt-4">
                @csrf
                <button type="submit" class="btn btn-primary">Continue</button>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Quotation Details</h3>
        </div>
        <div class="card-body">
            <p><strong>Project Name:</strong> {{ $quotation->quotation_name }}</p>
            <p><strong>Client Name:</strong> {{ $client->name }}</p>
            <p><strong>Start Date:</strong> {{ $quotation->start_date }}</p>
            @if ($quotation->end_date)
                <p><strong>End Date:</strong> {{ $quotation->end_date }}</p>
            @else
                <p><strong>End Date:</strong> Open Date</p>                
            @endif
            <p><strong>Final Invoice Date:</strong> {{ $quotation->final_invoice_date }}</p>
            <p><strong>Require Deposit:</strong> {{ $quotation->require_deposit ? 'Yes' : 'No' }}</p>
            @if ($quotation->require_deposit)
                <p><strong>Deposit Percentage:</strong> {{ $quotation->deposit_percentage }}%</p>
                <p><strong>Deposit Amount:</strong> ${{ $quotation->deposit_amount }}</p>
                <p><strong>Client Agrees to Deposit:</strong> {{ $quotation->client_agrees_deposit ? 'Yes' : 'No' }}</p>
            @endif
        </div>
    </div>
    <div class="card mt-4">
        <div class="card-header">
            <h3 class="card-title">Services</h3>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>Price</th>
                        <th>Fee Method</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($serviceDetails as $service)
                        <tr>
                            <td>{{ $service->service_name }}</td>
                            <td>{{ $service->price }}</td>
                            <td>{{ $service->pay_method }}</td>
                            <td>{{ $service->description }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
@endsection